// Code generated by generator.py. DO NOT EDIT.

package types

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

type ClustersDataSourceModel struct {
	Id                     types.String  `tfsdk:"id"`
	ParentId               types.String  `tfsdk:"parent_id"`
	ParentName             types.String  `tfsdk:"parent_name"`
	ParentDisplayName      types.String  `tfsdk:"parent_display_name"`
	ClusterType            types.String  `tfsdk:"cluster_type"`
	Delay                  types.Float64 `tfsdk:"delay"`
	OrgName                types.String  `tfsdk:"org_name"`
	CloudProvider          types.String  `tfsdk:"cloud_provider"`
	EnvironmentId          types.String  `tfsdk:"environment_id"`
	EnvironmentName        types.String  `tfsdk:"environment_name"`
	CloudRegion            types.String  `tfsdk:"cloud_region"`
	Project                types.String  `tfsdk:"project"`
	Name                   types.String  `tfsdk:"name"`
	Hash                   types.String  `tfsdk:"hash"`
	Engine                 types.String  `tfsdk:"engine"`
	Version                types.String  `tfsdk:"version"`
	TerminationPolicy      types.String  `tfsdk:"termination_policy"`
	TlsEnabled             types.Bool    `tfsdk:"tls_enabled"`
	NodePortEnabled        types.Bool    `tfsdk:"node_port_enabled"`
	Status                 types.String  `tfsdk:"status"`
	CreatedAt              types.String  `tfsdk:"created_at"`
	UpdatedAt              types.String  `tfsdk:"updated_at"`
	Mode                   types.String  `tfsdk:"mode"`
	ProxyEnabled           types.Bool    `tfsdk:"proxy_enabled"`
	Extra                  types.Dynamic `tfsdk:"extra"`
	SingleZone             types.Bool    `tfsdk:"single_zone"`
	PodAntiAffinityEnabled types.Bool    `tfsdk:"pod_anti_affinity_enabled"`
	NodeGroup              types.String  `tfsdk:"node_group"`
	CodeShort              types.String  `tfsdk:"code_short"`
	DisplayName            types.String  `tfsdk:"display_name"`
	Static                 types.Bool    `tfsdk:"static"`
	NetworkMode            types.String  `tfsdk:"network_mode"`
	AvailabilityZones      types.List    `tfsdk:"availability_zones"`
	ParamTpls              types.List    `tfsdk:"param_tpls"`
	Components             types.List    `tfsdk:"components"`
	InitOptions            types.List    `tfsdk:"init_options"`
	ServiceRefs            types.List    `tfsdk:"service_refs"`
	ReferencedBy           types.List    `tfsdk:"referenced_by"`
	License                types.Object  `tfsdk:"license"`
	Backup                 types.Object  `tfsdk:"backup"`
	ObjectStorageConfig    types.Object  `tfsdk:"object_storage_config"`
	MaintainceWindow       types.Object  `tfsdk:"maintaince_window"`
}

func (m *ClustersDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["id"]; ok && val != nil {
		m.Id = types.StringValue(val.(string))
	} else {
		m.Id = types.StringNull()
	}
	if val, ok := apiData["parentId"]; ok && val != nil {
		m.ParentId = types.StringValue(val.(string))
	} else {
		m.ParentId = types.StringNull()
	}
	if val, ok := apiData["parentName"]; ok && val != nil {
		m.ParentName = types.StringValue(val.(string))
	} else {
		m.ParentName = types.StringNull()
	}
	if val, ok := apiData["parentDisplayName"]; ok && val != nil {
		m.ParentDisplayName = types.StringValue(val.(string))
	} else {
		m.ParentDisplayName = types.StringNull()
	}
	if val, ok := apiData["clusterType"]; ok && val != nil {
		m.ClusterType = types.StringValue(val.(string))
	} else {
		m.ClusterType = types.StringNull()
	}
	if val, ok := apiData["delay"]; ok && val != nil {
		m.Delay = types.Float64Value(val.(float64))
	} else {
		m.Delay = types.Float64Null()
	}
	if val, ok := apiData["orgName"]; ok && val != nil {
		m.OrgName = types.StringValue(val.(string))
	} else {
		m.OrgName = types.StringNull()
	}
	if val, ok := apiData["cloudProvider"]; ok && val != nil {
		m.CloudProvider = types.StringValue(val.(string))
	} else {
		m.CloudProvider = types.StringNull()
	}
	if val, ok := apiData["environmentId"]; ok && val != nil {
		m.EnvironmentId = types.StringValue(val.(string))
	} else {
		m.EnvironmentId = types.StringNull()
	}
	if val, ok := apiData["environmentName"]; ok && val != nil {
		m.EnvironmentName = types.StringValue(val.(string))
	} else {
		m.EnvironmentName = types.StringNull()
	}
	if val, ok := apiData["cloudRegion"]; ok && val != nil {
		m.CloudRegion = types.StringValue(val.(string))
	} else {
		m.CloudRegion = types.StringNull()
	}
	if val, ok := apiData["project"]; ok && val != nil {
		m.Project = types.StringValue(val.(string))
	} else {
		m.Project = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["hash"]; ok && val != nil {
		m.Hash = types.StringValue(val.(string))
	} else {
		m.Hash = types.StringNull()
	}
	if val, ok := apiData["engine"]; ok && val != nil {
		m.Engine = types.StringValue(val.(string))
	} else {
		m.Engine = types.StringNull()
	}
	if val, ok := apiData["version"]; ok && val != nil {
		m.Version = types.StringValue(val.(string))
	} else {
		m.Version = types.StringNull()
	}
	if val, ok := apiData["terminationPolicy"]; ok && val != nil {
		m.TerminationPolicy = types.StringValue(val.(string))
	} else {
		m.TerminationPolicy = types.StringNull()
	}
	if val, ok := apiData["tlsEnabled"]; ok && val != nil {
		m.TlsEnabled = types.BoolValue(val.(bool))
	} else {
		m.TlsEnabled = types.BoolNull()
	}
	if val, ok := apiData["nodePortEnabled"]; ok && val != nil {
		m.NodePortEnabled = types.BoolValue(val.(bool))
	} else {
		m.NodePortEnabled = types.BoolNull()
	}
	if val, ok := apiData["status"]; ok && val != nil {
		m.Status = types.StringValue(val.(string))
	} else {
		m.Status = types.StringNull()
	}
	if val, ok := apiData["createdAt"]; ok && val != nil {
		m.CreatedAt = types.StringValue(val.(string))
	} else {
		m.CreatedAt = types.StringNull()
	}
	if val, ok := apiData["updatedAt"]; ok && val != nil {
		m.UpdatedAt = types.StringValue(val.(string))
	} else {
		m.UpdatedAt = types.StringNull()
	}
	if val, ok := apiData["mode"]; ok && val != nil {
		m.Mode = types.StringValue(val.(string))
	} else {
		m.Mode = types.StringNull()
	}
	if val, ok := apiData["proxyEnabled"]; ok && val != nil {
		m.ProxyEnabled = types.BoolValue(val.(bool))
	} else {
		m.ProxyEnabled = types.BoolNull()
	}
	if val, ok := apiData["extra"]; ok && val != nil {
		// Keep original value if it is valid, otherwise set null
		if m.Extra.IsUnknown() {
			m.Extra = basetypes.NewDynamicNull()
		}
	} else {
		if m.Extra.IsUnknown() {
			m.Extra = basetypes.NewDynamicNull()
		}
	}
	if val, ok := apiData["singleZone"]; ok && val != nil {
		m.SingleZone = types.BoolValue(val.(bool))
	} else {
		m.SingleZone = types.BoolNull()
	}
	if val, ok := apiData["podAntiAffinityEnabled"]; ok && val != nil {
		m.PodAntiAffinityEnabled = types.BoolValue(val.(bool))
	} else {
		m.PodAntiAffinityEnabled = types.BoolNull()
	}
	if val, ok := apiData["nodeGroup"]; ok && val != nil {
		m.NodeGroup = types.StringValue(val.(string))
	} else {
		m.NodeGroup = types.StringNull()
	}
	if val, ok := apiData["codeShort"]; ok && val != nil {
		m.CodeShort = types.StringValue(val.(string))
	} else {
		m.CodeShort = types.StringNull()
	}
	if val, ok := apiData["displayName"]; ok && val != nil {
		m.DisplayName = types.StringValue(val.(string))
	} else {
		m.DisplayName = types.StringNull()
	}
	if val, ok := apiData["static"]; ok && val != nil {
		m.Static = types.BoolValue(val.(bool))
	} else {
		m.Static = types.BoolNull()
	}
	if val, ok := apiData["networkMode"]; ok && val != nil {
		m.NetworkMode = types.StringValue(val.(string))
	} else {
		m.NetworkMode = types.StringNull()
	}
	if val, ok := apiData["availabilityZones"]; ok && val != nil {
		var items []attr.Value
		for _, item := range val.([]interface{}) {
			items = append(items, types.StringValue(item.(string)))
		}
		list, d := types.ListValue(types.StringType, items)
		diags.Append(d...)
		m.AvailabilityZones = list
	} else {
		m.AvailabilityZones = types.ListNull(types.StringType)
	}
	if val, ok := apiData["license"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel LicenseDataSourceModel
		if !m.License.IsNull() && !m.License.IsUnknown() {
			m.License.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.License = obj
	} else {
		m.License = types.ObjectNull(LicenseDataSourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["backup"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel BackupDataSourceModel
		if !m.Backup.IsNull() && !m.Backup.IsUnknown() {
			m.Backup.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.Backup = obj
	} else {
		m.Backup = types.ObjectNull(BackupDataSourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["objectStorageConfig"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ObjectStorageConfigDataSourceModel
		if !m.ObjectStorageConfig.IsNull() && !m.ObjectStorageConfig.IsUnknown() {
			m.ObjectStorageConfig.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ObjectStorageConfig = obj
	} else {
		m.ObjectStorageConfig = types.ObjectNull(ObjectStorageConfigDataSourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["maintainceWindow"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel MaintainceWindowDataSourceModel
		if !m.MaintainceWindow.IsNull() && !m.MaintainceWindow.IsUnknown() {
			m.MaintainceWindow.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.MaintainceWindow = obj
	} else {
		m.MaintainceWindow = types.ObjectNull(MaintainceWindowDataSourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["paramTpls"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ParamTplsDataSourceModel
		if !m.ParamTpls.IsNull() && !m.ParamTpls.IsUnknown() {
			m.ParamTpls.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ParamTplsDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ParamTplsDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.ParamTpls = list
	} else {
		m.ParamTpls = types.ListNull(types.ObjectType{AttrTypes: ParamTplsDataSourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["components"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ComponentsDataSourceModel
		if !m.Components.IsNull() && !m.Components.IsUnknown() {
			m.Components.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ComponentsDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ComponentsDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Components = list
	} else {
		m.Components = types.ListNull(types.ObjectType{AttrTypes: ComponentsDataSourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["initOptions"]; ok && val != nil {
		var items []attr.Value
		var oldElements []InitOptionsDataSourceModel
		if !m.InitOptions.IsNull() && !m.InitOptions.IsUnknown() {
			m.InitOptions.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel InitOptionsDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: InitOptionsDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.InitOptions = list
	} else {
		m.InitOptions = types.ListNull(types.ObjectType{AttrTypes: InitOptionsDataSourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["serviceRefs"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ServiceRefsDataSourceModel
		if !m.ServiceRefs.IsNull() && !m.ServiceRefs.IsUnknown() {
			m.ServiceRefs.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ServiceRefsDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ServiceRefsDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.ServiceRefs = list
	} else {
		m.ServiceRefs = types.ListNull(types.ObjectType{AttrTypes: ServiceRefsDataSourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["referencedBy"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ReferencedByDataSourceModel
		if !m.ReferencedBy.IsNull() && !m.ReferencedBy.IsUnknown() {
			m.ReferencedBy.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ReferencedByDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ReferencedByDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.ReferencedBy = list
	} else {
		m.ReferencedBy = types.ListNull(types.ObjectType{AttrTypes: ReferencedByDataSourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *ClustersDataSourceModel) Merge(remote *ClustersDataSourceModel) {
	if m.Id.IsNull() || m.Id.IsUnknown() {
		m.Id = remote.Id
	}
	if m.ParentId.IsNull() || m.ParentId.IsUnknown() {
		m.ParentId = remote.ParentId
	}
	if m.ParentName.IsNull() || m.ParentName.IsUnknown() {
		m.ParentName = remote.ParentName
	}
	if m.ParentDisplayName.IsNull() || m.ParentDisplayName.IsUnknown() {
		m.ParentDisplayName = remote.ParentDisplayName
	}
	if m.ClusterType.IsNull() || m.ClusterType.IsUnknown() {
		m.ClusterType = remote.ClusterType
	}
	if m.Delay.IsNull() || m.Delay.IsUnknown() {
		m.Delay = remote.Delay
	}
	if m.OrgName.IsNull() || m.OrgName.IsUnknown() {
		m.OrgName = remote.OrgName
	}
	if m.CloudProvider.IsNull() || m.CloudProvider.IsUnknown() {
		m.CloudProvider = remote.CloudProvider
	}
	if m.EnvironmentId.IsNull() || m.EnvironmentId.IsUnknown() {
		m.EnvironmentId = remote.EnvironmentId
	}
	if m.EnvironmentName.IsNull() || m.EnvironmentName.IsUnknown() {
		m.EnvironmentName = remote.EnvironmentName
	}
	if m.CloudRegion.IsNull() || m.CloudRegion.IsUnknown() {
		m.CloudRegion = remote.CloudRegion
	}
	if m.Project.IsNull() || m.Project.IsUnknown() {
		m.Project = remote.Project
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Hash.IsNull() || m.Hash.IsUnknown() {
		m.Hash = remote.Hash
	}
	if m.Engine.IsNull() || m.Engine.IsUnknown() {
		m.Engine = remote.Engine
	}
	if m.Version.IsNull() || m.Version.IsUnknown() {
		m.Version = remote.Version
	}
	if m.TerminationPolicy.IsNull() || m.TerminationPolicy.IsUnknown() {
		m.TerminationPolicy = remote.TerminationPolicy
	}
	if m.TlsEnabled.IsNull() || m.TlsEnabled.IsUnknown() {
		m.TlsEnabled = remote.TlsEnabled
	}
	if m.NodePortEnabled.IsNull() || m.NodePortEnabled.IsUnknown() {
		m.NodePortEnabled = remote.NodePortEnabled
	}
	if m.Status.IsNull() || m.Status.IsUnknown() {
		m.Status = remote.Status
	}
	if m.CreatedAt.IsNull() || m.CreatedAt.IsUnknown() {
		m.CreatedAt = remote.CreatedAt
	}
	if m.UpdatedAt.IsNull() || m.UpdatedAt.IsUnknown() {
		m.UpdatedAt = remote.UpdatedAt
	}
	if m.Mode.IsNull() || m.Mode.IsUnknown() {
		m.Mode = remote.Mode
	}
	if m.ProxyEnabled.IsNull() || m.ProxyEnabled.IsUnknown() {
		m.ProxyEnabled = remote.ProxyEnabled
	}
	if m.Extra.IsNull() || m.Extra.IsUnknown() {
		m.Extra = remote.Extra
	}
	if m.SingleZone.IsNull() || m.SingleZone.IsUnknown() {
		m.SingleZone = remote.SingleZone
	}
	if m.PodAntiAffinityEnabled.IsNull() || m.PodAntiAffinityEnabled.IsUnknown() {
		m.PodAntiAffinityEnabled = remote.PodAntiAffinityEnabled
	}
	if m.NodeGroup.IsNull() || m.NodeGroup.IsUnknown() {
		m.NodeGroup = remote.NodeGroup
	}
	if m.CodeShort.IsNull() || m.CodeShort.IsUnknown() {
		m.CodeShort = remote.CodeShort
	}
	if m.DisplayName.IsNull() || m.DisplayName.IsUnknown() {
		m.DisplayName = remote.DisplayName
	}
	if m.Static.IsNull() || m.Static.IsUnknown() {
		m.Static = remote.Static
	}
	if m.NetworkMode.IsNull() || m.NetworkMode.IsUnknown() {
		m.NetworkMode = remote.NetworkMode
	}
	if m.AvailabilityZones.IsNull() || m.AvailabilityZones.IsUnknown() {
		m.AvailabilityZones = remote.AvailabilityZones
	}
	if m.License.IsNull() || m.License.IsUnknown() {
		m.License = remote.License
	} else {
		var localObj LicenseDataSourceModel
		var remoteObj LicenseDataSourceModel
		if !m.License.IsNull() && !m.License.IsUnknown() {
			m.License.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.License.IsNull() && !remote.License.IsUnknown() {
			remote.License.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.License = obj
		}
	}
	if m.Backup.IsNull() || m.Backup.IsUnknown() {
		m.Backup = remote.Backup
	} else {
		var localObj BackupDataSourceModel
		var remoteObj BackupDataSourceModel
		if !m.Backup.IsNull() && !m.Backup.IsUnknown() {
			m.Backup.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.Backup.IsNull() && !remote.Backup.IsUnknown() {
			remote.Backup.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.Backup = obj
		}
	}
	if m.ObjectStorageConfig.IsNull() || m.ObjectStorageConfig.IsUnknown() {
		m.ObjectStorageConfig = remote.ObjectStorageConfig
	} else {
		var localObj ObjectStorageConfigDataSourceModel
		var remoteObj ObjectStorageConfigDataSourceModel
		if !m.ObjectStorageConfig.IsNull() && !m.ObjectStorageConfig.IsUnknown() {
			m.ObjectStorageConfig.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ObjectStorageConfig.IsNull() && !remote.ObjectStorageConfig.IsUnknown() {
			remote.ObjectStorageConfig.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ObjectStorageConfig = obj
		}
	}
	if m.MaintainceWindow.IsNull() || m.MaintainceWindow.IsUnknown() {
		m.MaintainceWindow = remote.MaintainceWindow
	} else {
		var localObj MaintainceWindowDataSourceModel
		var remoteObj MaintainceWindowDataSourceModel
		if !m.MaintainceWindow.IsNull() && !m.MaintainceWindow.IsUnknown() {
			m.MaintainceWindow.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.MaintainceWindow.IsNull() && !remote.MaintainceWindow.IsUnknown() {
			remote.MaintainceWindow.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.MaintainceWindow = obj
		}
	}
	if m.ParamTpls.IsNull() || m.ParamTpls.IsUnknown() {
		m.ParamTpls = remote.ParamTpls
	} else {
		var localList []ParamTplsDataSourceModel
		var remoteList []ParamTplsDataSourceModel
		if !m.ParamTpls.IsNull() && !m.ParamTpls.IsUnknown() {
			m.ParamTpls.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.ParamTpls.IsNull() && !remote.ParamTpls.IsUnknown() {
			remote.ParamTpls.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ParamTplsDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.ParamTpls = list
		}
	}
	if m.Components.IsNull() || m.Components.IsUnknown() {
		m.Components = remote.Components
	} else {
		var localList []ComponentsDataSourceModel
		var remoteList []ComponentsDataSourceModel
		if !m.Components.IsNull() && !m.Components.IsUnknown() {
			m.Components.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Components.IsNull() && !remote.Components.IsUnknown() {
			remote.Components.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ComponentsDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Components = list
		}
	}
	if m.InitOptions.IsNull() || m.InitOptions.IsUnknown() {
		m.InitOptions = remote.InitOptions
	} else {
		var localList []InitOptionsDataSourceModel
		var remoteList []InitOptionsDataSourceModel
		if !m.InitOptions.IsNull() && !m.InitOptions.IsUnknown() {
			m.InitOptions.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.InitOptions.IsNull() && !remote.InitOptions.IsUnknown() {
			remote.InitOptions.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: InitOptionsDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.InitOptions = list
		}
	}
	if m.ServiceRefs.IsNull() || m.ServiceRefs.IsUnknown() {
		m.ServiceRefs = remote.ServiceRefs
	} else {
		var localList []ServiceRefsDataSourceModel
		var remoteList []ServiceRefsDataSourceModel
		if !m.ServiceRefs.IsNull() && !m.ServiceRefs.IsUnknown() {
			m.ServiceRefs.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.ServiceRefs.IsNull() && !remote.ServiceRefs.IsUnknown() {
			remote.ServiceRefs.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ServiceRefsDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.ServiceRefs = list
		}
	}
	if m.ReferencedBy.IsNull() || m.ReferencedBy.IsUnknown() {
		m.ReferencedBy = remote.ReferencedBy
	} else {
		var localList []ReferencedByDataSourceModel
		var remoteList []ReferencedByDataSourceModel
		if !m.ReferencedBy.IsNull() && !m.ReferencedBy.IsUnknown() {
			m.ReferencedBy.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.ReferencedBy.IsNull() && !remote.ReferencedBy.IsUnknown() {
			remote.ReferencedBy.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ReferencedByDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.ReferencedBy = list
		}
	}
}

type ParamTplsDataSourceModel struct {
	Component         types.String `tfsdk:"component"`
	ParamTplName      types.String `tfsdk:"param_tpl_name"`
	ParamTplId        types.String `tfsdk:"param_tpl_id"`
	OrgName           types.String `tfsdk:"org_name"`
	ParamTplPartition types.String `tfsdk:"param_tpl_partition"`
}

func (v ParamTplsDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"component":           types.StringType,
		"param_tpl_name":      types.StringType,
		"param_tpl_id":        types.StringType,
		"org_name":            types.StringType,
		"param_tpl_partition": types.StringType,
	}
}

func (m *ParamTplsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	if val, ok := apiData["paramTplName"]; ok && val != nil {
		m.ParamTplName = types.StringValue(val.(string))
	} else {
		m.ParamTplName = types.StringNull()
	}
	if val, ok := apiData["paramTplID"]; ok && val != nil {
		m.ParamTplId = types.StringValue(val.(string))
	} else {
		m.ParamTplId = types.StringNull()
	}
	if val, ok := apiData["orgName"]; ok && val != nil {
		m.OrgName = types.StringValue(val.(string))
	} else {
		m.OrgName = types.StringNull()
	}
	if val, ok := apiData["paramTplPartition"]; ok && val != nil {
		m.ParamTplPartition = types.StringValue(val.(string))
	} else {
		m.ParamTplPartition = types.StringNull()
	}

	return diags
}

func (m *ParamTplsDataSourceModel) Merge(remote *ParamTplsDataSourceModel) {
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.ParamTplName.IsNull() || m.ParamTplName.IsUnknown() {
		m.ParamTplName = remote.ParamTplName
	}
	if m.ParamTplId.IsNull() || m.ParamTplId.IsUnknown() {
		m.ParamTplId = remote.ParamTplId
	}
	if m.OrgName.IsNull() || m.OrgName.IsUnknown() {
		m.OrgName = remote.OrgName
	}
	if m.ParamTplPartition.IsNull() || m.ParamTplPartition.IsUnknown() {
		m.ParamTplPartition = remote.ParamTplPartition
	}
}

type ComponentsDataSourceModel struct {
	Name                    types.String  `tfsdk:"name"`
	Component               types.String  `tfsdk:"component"`
	CompNum                 types.Int64   `tfsdk:"comp_num"`
	Replicas                types.Int64   `tfsdk:"replicas"`
	ClassCode               types.String  `tfsdk:"class_code"`
	Cpu                     types.Float64 `tfsdk:"cpu"`
	Memory                  types.Float64 `tfsdk:"memory"`
	StorageClass            types.String  `tfsdk:"storage_class"`
	CodeShort               types.String  `tfsdk:"code_short"`
	SystemAccountSecretName types.String  `tfsdk:"system_account_secret_name"`
	Volumes                 types.List    `tfsdk:"volumes"`
}

func (v ComponentsDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":                       types.StringType,
		"component":                  types.StringType,
		"comp_num":                   types.Int64Type,
		"replicas":                   types.Int64Type,
		"class_code":                 types.StringType,
		"cpu":                        types.Float64Type,
		"memory":                     types.Float64Type,
		"storage_class":              types.StringType,
		"code_short":                 types.StringType,
		"system_account_secret_name": types.StringType,
		"volumes":                    types.ListType{ElemType: types.ObjectType{AttrTypes: VolumesDataSourceModel{}.AttributeTypes()}},
	}
}

func (m *ComponentsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	if val, ok := apiData["compNum"]; ok && val != nil {
		m.CompNum = types.Int64Value(int64(val.(float64)))
	} else {
		m.CompNum = types.Int64Null()
	}
	if val, ok := apiData["replicas"]; ok && val != nil {
		m.Replicas = types.Int64Value(int64(val.(float64)))
	} else {
		m.Replicas = types.Int64Null()
	}
	if val, ok := apiData["classCode"]; ok && val != nil {
		m.ClassCode = types.StringValue(val.(string))
	} else {
		m.ClassCode = types.StringNull()
	}
	if val, ok := apiData["cpu"]; ok && val != nil {
		m.Cpu = types.Float64Value(val.(float64))
	} else {
		m.Cpu = types.Float64Null()
	}
	if val, ok := apiData["memory"]; ok && val != nil {
		m.Memory = types.Float64Value(val.(float64))
	} else {
		m.Memory = types.Float64Null()
	}
	if val, ok := apiData["storageClass"]; ok && val != nil {
		m.StorageClass = types.StringValue(val.(string))
	} else {
		m.StorageClass = types.StringNull()
	}
	if val, ok := apiData["codeShort"]; ok && val != nil {
		m.CodeShort = types.StringValue(val.(string))
	} else {
		m.CodeShort = types.StringNull()
	}
	if val, ok := apiData["systemAccountSecretName"]; ok && val != nil {
		m.SystemAccountSecretName = types.StringValue(val.(string))
	} else {
		m.SystemAccountSecretName = types.StringNull()
	}
	if val, ok := apiData["volumes"]; ok && val != nil {
		var items []attr.Value
		var oldElements []VolumesDataSourceModel
		if !m.Volumes.IsNull() && !m.Volumes.IsUnknown() {
			m.Volumes.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel VolumesDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: VolumesDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Volumes = list
	} else {
		m.Volumes = types.ListNull(types.ObjectType{AttrTypes: VolumesDataSourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *ComponentsDataSourceModel) Merge(remote *ComponentsDataSourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.CompNum.IsNull() || m.CompNum.IsUnknown() {
		m.CompNum = remote.CompNum
	}
	if m.Replicas.IsNull() || m.Replicas.IsUnknown() {
		m.Replicas = remote.Replicas
	}
	if m.ClassCode.IsNull() || m.ClassCode.IsUnknown() {
		m.ClassCode = remote.ClassCode
	}
	if m.Cpu.IsNull() || m.Cpu.IsUnknown() {
		m.Cpu = remote.Cpu
	}
	if m.Memory.IsNull() || m.Memory.IsUnknown() {
		m.Memory = remote.Memory
	}
	if m.StorageClass.IsNull() || m.StorageClass.IsUnknown() {
		m.StorageClass = remote.StorageClass
	}
	if m.CodeShort.IsNull() || m.CodeShort.IsUnknown() {
		m.CodeShort = remote.CodeShort
	}
	if m.SystemAccountSecretName.IsNull() || m.SystemAccountSecretName.IsUnknown() {
		m.SystemAccountSecretName = remote.SystemAccountSecretName
	}
	if m.Volumes.IsNull() || m.Volumes.IsUnknown() {
		m.Volumes = remote.Volumes
	} else {
		var localList []VolumesDataSourceModel
		var remoteList []VolumesDataSourceModel
		if !m.Volumes.IsNull() && !m.Volumes.IsUnknown() {
			m.Volumes.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Volumes.IsNull() && !remote.Volumes.IsUnknown() {
			remote.Volumes.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: VolumesDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Volumes = list
		}
	}
}

type VolumesDataSourceModel struct {
	Name       types.String  `tfsdk:"name"`
	Storage    types.Float64 `tfsdk:"storage"`
	IoLimits   types.Object  `tfsdk:"io_limits"`
	IoReserves types.Object  `tfsdk:"io_reserves"`
}

func (v VolumesDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":        types.StringType,
		"storage":     types.Float64Type,
		"io_limits":   types.ObjectType{AttrTypes: IoLimitsDataSourceModel{}.AttributeTypes()},
		"io_reserves": types.ObjectType{AttrTypes: IoReservesDataSourceModel{}.AttributeTypes()},
	}
}

func (m *VolumesDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["storage"]; ok && val != nil {
		m.Storage = types.Float64Value(val.(float64))
	} else {
		m.Storage = types.Float64Null()
	}
	if val, ok := apiData["ioLimits"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel IoLimitsDataSourceModel
		if !m.IoLimits.IsNull() && !m.IoLimits.IsUnknown() {
			m.IoLimits.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.IoLimits = obj
	} else {
		m.IoLimits = types.ObjectNull(IoLimitsDataSourceModel{}.AttributeTypes())
	}
	if val, ok := apiData["ioReserves"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel IoReservesDataSourceModel
		if !m.IoReserves.IsNull() && !m.IoReserves.IsUnknown() {
			m.IoReserves.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.IoReserves = obj
	} else {
		m.IoReserves = types.ObjectNull(IoReservesDataSourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *VolumesDataSourceModel) Merge(remote *VolumesDataSourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Storage.IsNull() || m.Storage.IsUnknown() {
		m.Storage = remote.Storage
	}
	if m.IoLimits.IsNull() || m.IoLimits.IsUnknown() {
		m.IoLimits = remote.IoLimits
	} else {
		var localObj IoLimitsDataSourceModel
		var remoteObj IoLimitsDataSourceModel
		if !m.IoLimits.IsNull() && !m.IoLimits.IsUnknown() {
			m.IoLimits.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.IoLimits.IsNull() && !remote.IoLimits.IsUnknown() {
			remote.IoLimits.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.IoLimits = obj
		}
	}
	if m.IoReserves.IsNull() || m.IoReserves.IsUnknown() {
		m.IoReserves = remote.IoReserves
	} else {
		var localObj IoReservesDataSourceModel
		var remoteObj IoReservesDataSourceModel
		if !m.IoReserves.IsNull() && !m.IoReserves.IsUnknown() {
			m.IoReserves.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.IoReserves.IsNull() && !remote.IoReserves.IsUnknown() {
			remote.IoReserves.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.IoReserves = obj
		}
	}
}

type IoLimitsDataSourceModel struct {
	ReadIops  types.Int64 `tfsdk:"read_iops"`
	WriteIops types.Int64 `tfsdk:"write_iops"`
	ReadBps   types.Int64 `tfsdk:"read_bps"`
	WriteBps  types.Int64 `tfsdk:"write_bps"`
}

func (v IoLimitsDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"read_iops":  types.Int64Type,
		"write_iops": types.Int64Type,
		"read_bps":   types.Int64Type,
		"write_bps":  types.Int64Type,
	}
}

func (m *IoLimitsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["readIOPS"]; ok && val != nil {
		m.ReadIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadIops = types.Int64Null()
	}
	if val, ok := apiData["writeIOPS"]; ok && val != nil {
		m.WriteIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteIops = types.Int64Null()
	}
	if val, ok := apiData["readBPS"]; ok && val != nil {
		m.ReadBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadBps = types.Int64Null()
	}
	if val, ok := apiData["writeBPS"]; ok && val != nil {
		m.WriteBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteBps = types.Int64Null()
	}

	return diags
}

func (m *IoLimitsDataSourceModel) Merge(remote *IoLimitsDataSourceModel) {
	if m.ReadIops.IsNull() || m.ReadIops.IsUnknown() {
		m.ReadIops = remote.ReadIops
	}
	if m.WriteIops.IsNull() || m.WriteIops.IsUnknown() {
		m.WriteIops = remote.WriteIops
	}
	if m.ReadBps.IsNull() || m.ReadBps.IsUnknown() {
		m.ReadBps = remote.ReadBps
	}
	if m.WriteBps.IsNull() || m.WriteBps.IsUnknown() {
		m.WriteBps = remote.WriteBps
	}
}

type IoReservesDataSourceModel struct {
	ReadIops  types.Int64 `tfsdk:"read_iops"`
	WriteIops types.Int64 `tfsdk:"write_iops"`
	ReadBps   types.Int64 `tfsdk:"read_bps"`
	WriteBps  types.Int64 `tfsdk:"write_bps"`
}

func (v IoReservesDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"read_iops":  types.Int64Type,
		"write_iops": types.Int64Type,
		"read_bps":   types.Int64Type,
		"write_bps":  types.Int64Type,
	}
}

func (m *IoReservesDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["readIOPS"]; ok && val != nil {
		m.ReadIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadIops = types.Int64Null()
	}
	if val, ok := apiData["writeIOPS"]; ok && val != nil {
		m.WriteIops = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteIops = types.Int64Null()
	}
	if val, ok := apiData["readBPS"]; ok && val != nil {
		m.ReadBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.ReadBps = types.Int64Null()
	}
	if val, ok := apiData["writeBPS"]; ok && val != nil {
		m.WriteBps = types.Int64Value(int64(val.(float64)))
	} else {
		m.WriteBps = types.Int64Null()
	}

	return diags
}

func (m *IoReservesDataSourceModel) Merge(remote *IoReservesDataSourceModel) {
	if m.ReadIops.IsNull() || m.ReadIops.IsUnknown() {
		m.ReadIops = remote.ReadIops
	}
	if m.WriteIops.IsNull() || m.WriteIops.IsUnknown() {
		m.WriteIops = remote.WriteIops
	}
	if m.ReadBps.IsNull() || m.ReadBps.IsUnknown() {
		m.ReadBps = remote.ReadBps
	}
	if m.WriteBps.IsNull() || m.WriteBps.IsUnknown() {
		m.WriteBps = remote.WriteBps
	}
}

type InitOptionsDataSourceModel struct {
	Component  types.String `tfsdk:"component"`
	InitParams types.Map    `tfsdk:"init_params"`
	SpecName   types.String `tfsdk:"spec_name"`
}

func (v InitOptionsDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"component":   types.StringType,
		"init_params": types.MapType{ElemType: types.StringType},
		"spec_name":   types.StringType,
	}
}

func (m *InitOptionsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	if val, ok := apiData["initParams"]; ok && val != nil {
		mapValues := make(map[string]attr.Value)
		for k, v := range val.(map[string]interface{}) {
			mapValues[k] = types.StringValue(v.(string))
		}
		m.InitParams, _ = types.MapValue(types.StringType, mapValues)
	} else {
		m.InitParams = types.MapNull(types.StringType)
	}
	if val, ok := apiData["specName"]; ok && val != nil {
		m.SpecName = types.StringValue(val.(string))
	} else {
		m.SpecName = types.StringNull()
	}

	return diags
}

func (m *InitOptionsDataSourceModel) Merge(remote *InitOptionsDataSourceModel) {
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.InitParams.IsNull() || m.InitParams.IsUnknown() {
		m.InitParams = remote.InitParams
	}
	if m.SpecName.IsNull() || m.SpecName.IsUnknown() {
		m.SpecName = remote.SpecName
	}
}

type ServiceRefsDataSourceModel struct {
	Name              types.String `tfsdk:"name"`
	Cluster           types.String `tfsdk:"cluster"`
	ServiceDescriptor types.Object `tfsdk:"service_descriptor"`
}

func (v ServiceRefsDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":               types.StringType,
		"cluster":            types.StringType,
		"service_descriptor": types.ObjectType{AttrTypes: ServiceDescriptorDataSourceModel{}.AttributeTypes()},
	}
}

func (m *ServiceRefsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["cluster"]; ok && val != nil {
		m.Cluster = types.StringValue(val.(string))
	} else {
		m.Cluster = types.StringNull()
	}
	if val, ok := apiData["serviceDescriptor"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceDescriptorDataSourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceDescriptor = obj
	} else {
		m.ServiceDescriptor = types.ObjectNull(ServiceDescriptorDataSourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ServiceRefsDataSourceModel) Merge(remote *ServiceRefsDataSourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Cluster.IsNull() || m.Cluster.IsUnknown() {
		m.Cluster = remote.Cluster
	}
	if m.ServiceDescriptor.IsNull() || m.ServiceDescriptor.IsUnknown() {
		m.ServiceDescriptor = remote.ServiceDescriptor
	} else {
		var localObj ServiceDescriptorDataSourceModel
		var remoteObj ServiceDescriptorDataSourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceDescriptor.IsNull() && !remote.ServiceDescriptor.IsUnknown() {
			remote.ServiceDescriptor.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceDescriptor = obj
		}
	}
}

type ServiceDescriptorDataSourceModel struct {
	Host     types.String `tfsdk:"host"`
	Port     types.String `tfsdk:"port"`
	Endpoint types.String `tfsdk:"endpoint"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
}

func (v ServiceDescriptorDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"host":     types.StringType,
		"port":     types.StringType,
		"endpoint": types.StringType,
		"username": types.StringType,
		"password": types.StringType,
	}
}

func (m *ServiceDescriptorDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["host"]; ok && val != nil {
		m.Host = types.StringValue(val.(string))
	} else {
		m.Host = types.StringNull()
	}
	if val, ok := apiData["port"]; ok && val != nil {
		m.Port = types.StringValue(val.(string))
	} else {
		m.Port = types.StringNull()
	}
	if val, ok := apiData["endpoint"]; ok && val != nil {
		m.Endpoint = types.StringValue(val.(string))
	} else {
		m.Endpoint = types.StringNull()
	}
	if val, ok := apiData["username"]; ok && val != nil {
		m.Username = types.StringValue(val.(string))
	} else {
		m.Username = types.StringNull()
	}
	if val, ok := apiData["password"]; ok && val != nil {
		m.Password = types.StringValue(val.(string))
	} else {
		m.Password = types.StringNull()
	}

	return diags
}

func (m *ServiceDescriptorDataSourceModel) Merge(remote *ServiceDescriptorDataSourceModel) {
	if m.Host.IsNull() || m.Host.IsUnknown() {
		m.Host = remote.Host
	}
	if m.Port.IsNull() || m.Port.IsUnknown() {
		m.Port = remote.Port
	}
	if m.Endpoint.IsNull() || m.Endpoint.IsUnknown() {
		m.Endpoint = remote.Endpoint
	}
	if m.Username.IsNull() || m.Username.IsUnknown() {
		m.Username = remote.Username
	}
	if m.Password.IsNull() || m.Password.IsUnknown() {
		m.Password = remote.Password
	}
}

type ReferencedByDataSourceModel struct {
	Name              types.String `tfsdk:"name"`
	Cluster           types.String `tfsdk:"cluster"`
	ServiceDescriptor types.Object `tfsdk:"service_descriptor"`
}

func (v ReferencedByDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":               types.StringType,
		"cluster":            types.StringType,
		"service_descriptor": types.ObjectType{AttrTypes: ServiceDescriptorDataSourceModel{}.AttributeTypes()},
	}
}

func (m *ReferencedByDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["cluster"]; ok && val != nil {
		m.Cluster = types.StringValue(val.(string))
	} else {
		m.Cluster = types.StringNull()
	}
	if val, ok := apiData["serviceDescriptor"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceDescriptorDataSourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceDescriptor = obj
	} else {
		m.ServiceDescriptor = types.ObjectNull(ServiceDescriptorDataSourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ReferencedByDataSourceModel) Merge(remote *ReferencedByDataSourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Cluster.IsNull() || m.Cluster.IsUnknown() {
		m.Cluster = remote.Cluster
	}
	if m.ServiceDescriptor.IsNull() || m.ServiceDescriptor.IsUnknown() {
		m.ServiceDescriptor = remote.ServiceDescriptor
	} else {
		var localObj ServiceDescriptorDataSourceModel
		var remoteObj ServiceDescriptorDataSourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceDescriptor.IsNull() && !remote.ServiceDescriptor.IsUnknown() {
			remote.ServiceDescriptor.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceDescriptor = obj
		}
	}
}

type LicenseDataSourceModel struct {
	Id        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	ExpiredAt types.String `tfsdk:"expired_at"`
	Key       types.String `tfsdk:"key"`
	Keys      types.Map    `tfsdk:"keys"`
}

func (v LicenseDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"id":         types.StringType,
		"name":       types.StringType,
		"expired_at": types.StringType,
		"key":        types.StringType,
		"keys":       types.MapType{ElemType: types.StringType},
	}
}

func (m *LicenseDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["id"]; ok && val != nil {
		m.Id = types.StringValue(val.(string))
	} else {
		m.Id = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["expiredAt"]; ok && val != nil {
		m.ExpiredAt = types.StringValue(val.(string))
	} else {
		m.ExpiredAt = types.StringNull()
	}
	if val, ok := apiData["key"]; ok && val != nil {
		m.Key = types.StringValue(val.(string))
	} else {
		m.Key = types.StringNull()
	}
	if val, ok := apiData["keys"]; ok && val != nil {
		mapValues := make(map[string]attr.Value)
		for k, v := range val.(map[string]interface{}) {
			mapValues[k] = types.StringValue(v.(string))
		}
		m.Keys, _ = types.MapValue(types.StringType, mapValues)
	} else {
		m.Keys = types.MapNull(types.StringType)
	}

	return diags
}

func (m *LicenseDataSourceModel) Merge(remote *LicenseDataSourceModel) {
	if m.Id.IsNull() || m.Id.IsUnknown() {
		m.Id = remote.Id
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.ExpiredAt.IsNull() || m.ExpiredAt.IsUnknown() {
		m.ExpiredAt = remote.ExpiredAt
	}
	if m.Key.IsNull() || m.Key.IsUnknown() {
		m.Key = remote.Key
	}
	if m.Keys.IsNull() || m.Keys.IsUnknown() {
		m.Keys = remote.Keys
	}
}

type BackupDataSourceModel struct {
	PitrEnabled               types.Bool   `tfsdk:"pitr_enabled"`
	ContinuousBackupMethod    types.String `tfsdk:"continuous_backup_method"`
	AutoBackup                types.Bool   `tfsdk:"auto_backup"`
	AutoBackupMethod          types.String `tfsdk:"auto_backup_method"`
	BackupRepo                types.String `tfsdk:"backup_repo"`
	CronExpression            types.String `tfsdk:"cron_expression"`
	RetentionPeriod           types.String `tfsdk:"retention_period"`
	RetentionPolicy           types.String `tfsdk:"retention_policy"`
	SnapshotVolumes           types.Bool   `tfsdk:"snapshot_volumes"`
	IncrementalBackupEnabled  types.Bool   `tfsdk:"incremental_backup_enabled"`
	IncrementalCronExpression types.String `tfsdk:"incremental_cron_expression"`
}

func (v BackupDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"pitr_enabled":                types.BoolType,
		"continuous_backup_method":    types.StringType,
		"auto_backup":                 types.BoolType,
		"auto_backup_method":          types.StringType,
		"backup_repo":                 types.StringType,
		"cron_expression":             types.StringType,
		"retention_period":            types.StringType,
		"retention_policy":            types.StringType,
		"snapshot_volumes":            types.BoolType,
		"incremental_backup_enabled":  types.BoolType,
		"incremental_cron_expression": types.StringType,
	}
}

func (m *BackupDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["pitrEnabled"]; ok && val != nil {
		m.PitrEnabled = types.BoolValue(val.(bool))
	} else {
		m.PitrEnabled = types.BoolNull()
	}
	if val, ok := apiData["continuousBackupMethod"]; ok && val != nil {
		m.ContinuousBackupMethod = types.StringValue(val.(string))
	} else {
		m.ContinuousBackupMethod = types.StringNull()
	}
	if val, ok := apiData["autoBackup"]; ok && val != nil {
		m.AutoBackup = types.BoolValue(val.(bool))
	} else {
		m.AutoBackup = types.BoolNull()
	}
	if val, ok := apiData["autoBackupMethod"]; ok && val != nil {
		m.AutoBackupMethod = types.StringValue(val.(string))
	} else {
		m.AutoBackupMethod = types.StringNull()
	}
	if val, ok := apiData["backupRepo"]; ok && val != nil {
		m.BackupRepo = types.StringValue(val.(string))
	} else {
		m.BackupRepo = types.StringNull()
	}
	if val, ok := apiData["cronExpression"]; ok && val != nil {
		m.CronExpression = types.StringValue(val.(string))
	} else {
		m.CronExpression = types.StringNull()
	}
	if val, ok := apiData["retentionPeriod"]; ok && val != nil {
		m.RetentionPeriod = types.StringValue(val.(string))
	} else {
		m.RetentionPeriod = types.StringNull()
	}
	if val, ok := apiData["retentionPolicy"]; ok && val != nil {
		m.RetentionPolicy = types.StringValue(val.(string))
	} else {
		m.RetentionPolicy = types.StringNull()
	}
	if val, ok := apiData["snapshotVolumes"]; ok && val != nil {
		m.SnapshotVolumes = types.BoolValue(val.(bool))
	} else {
		m.SnapshotVolumes = types.BoolNull()
	}
	if val, ok := apiData["incrementalBackupEnabled"]; ok && val != nil {
		m.IncrementalBackupEnabled = types.BoolValue(val.(bool))
	} else {
		m.IncrementalBackupEnabled = types.BoolNull()
	}
	if val, ok := apiData["incrementalCronExpression"]; ok && val != nil {
		m.IncrementalCronExpression = types.StringValue(val.(string))
	} else {
		m.IncrementalCronExpression = types.StringNull()
	}

	return diags
}

func (m *BackupDataSourceModel) Merge(remote *BackupDataSourceModel) {
	if m.PitrEnabled.IsNull() || m.PitrEnabled.IsUnknown() {
		m.PitrEnabled = remote.PitrEnabled
	}
	if m.ContinuousBackupMethod.IsNull() || m.ContinuousBackupMethod.IsUnknown() {
		m.ContinuousBackupMethod = remote.ContinuousBackupMethod
	}
	if m.AutoBackup.IsNull() || m.AutoBackup.IsUnknown() {
		m.AutoBackup = remote.AutoBackup
	}
	if m.AutoBackupMethod.IsNull() || m.AutoBackupMethod.IsUnknown() {
		m.AutoBackupMethod = remote.AutoBackupMethod
	}
	if m.BackupRepo.IsNull() || m.BackupRepo.IsUnknown() {
		m.BackupRepo = remote.BackupRepo
	}
	if m.CronExpression.IsNull() || m.CronExpression.IsUnknown() {
		m.CronExpression = remote.CronExpression
	}
	if m.RetentionPeriod.IsNull() || m.RetentionPeriod.IsUnknown() {
		m.RetentionPeriod = remote.RetentionPeriod
	}
	if m.RetentionPolicy.IsNull() || m.RetentionPolicy.IsUnknown() {
		m.RetentionPolicy = remote.RetentionPolicy
	}
	if m.SnapshotVolumes.IsNull() || m.SnapshotVolumes.IsUnknown() {
		m.SnapshotVolumes = remote.SnapshotVolumes
	}
	if m.IncrementalBackupEnabled.IsNull() || m.IncrementalBackupEnabled.IsUnknown() {
		m.IncrementalBackupEnabled = remote.IncrementalBackupEnabled
	}
	if m.IncrementalCronExpression.IsNull() || m.IncrementalCronExpression.IsUnknown() {
		m.IncrementalCronExpression = remote.IncrementalCronExpression
	}
}

type ObjectStorageConfigDataSourceModel struct {
	Bucket       types.String `tfsdk:"bucket"`
	UsePathStyle types.Bool   `tfsdk:"use_path_style"`
	Region       types.String `tfsdk:"region"`
	ServiceRef   types.Object `tfsdk:"service_ref"`
}

func (v ObjectStorageConfigDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"bucket":         types.StringType,
		"use_path_style": types.BoolType,
		"region":         types.StringType,
		"service_ref":    types.ObjectType{AttrTypes: ServiceRefDataSourceModel{}.AttributeTypes()},
	}
}

func (m *ObjectStorageConfigDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["bucket"]; ok && val != nil {
		m.Bucket = types.StringValue(val.(string))
	} else {
		m.Bucket = types.StringNull()
	}
	if val, ok := apiData["usePathStyle"]; ok && val != nil {
		m.UsePathStyle = types.BoolValue(val.(bool))
	} else {
		m.UsePathStyle = types.BoolNull()
	}
	if val, ok := apiData["region"]; ok && val != nil {
		m.Region = types.StringValue(val.(string))
	} else {
		m.Region = types.StringNull()
	}
	if val, ok := apiData["serviceRef"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceRefDataSourceModel
		if !m.ServiceRef.IsNull() && !m.ServiceRef.IsUnknown() {
			m.ServiceRef.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceRef = obj
	} else {
		m.ServiceRef = types.ObjectNull(ServiceRefDataSourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ObjectStorageConfigDataSourceModel) Merge(remote *ObjectStorageConfigDataSourceModel) {
	if m.Bucket.IsNull() || m.Bucket.IsUnknown() {
		m.Bucket = remote.Bucket
	}
	if m.UsePathStyle.IsNull() || m.UsePathStyle.IsUnknown() {
		m.UsePathStyle = remote.UsePathStyle
	}
	if m.Region.IsNull() || m.Region.IsUnknown() {
		m.Region = remote.Region
	}
	if m.ServiceRef.IsNull() || m.ServiceRef.IsUnknown() {
		m.ServiceRef = remote.ServiceRef
	} else {
		var localObj ServiceRefDataSourceModel
		var remoteObj ServiceRefDataSourceModel
		if !m.ServiceRef.IsNull() && !m.ServiceRef.IsUnknown() {
			m.ServiceRef.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceRef.IsNull() && !remote.ServiceRef.IsUnknown() {
			remote.ServiceRef.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceRef = obj
		}
	}
}

type ServiceRefDataSourceModel struct {
	Name              types.String `tfsdk:"name"`
	Cluster           types.String `tfsdk:"cluster"`
	ServiceDescriptor types.Object `tfsdk:"service_descriptor"`
}

func (v ServiceRefDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":               types.StringType,
		"cluster":            types.StringType,
		"service_descriptor": types.ObjectType{AttrTypes: ServiceDescriptorDataSourceModel{}.AttributeTypes()},
	}
}

func (m *ServiceRefDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["cluster"]; ok && val != nil {
		m.Cluster = types.StringValue(val.(string))
	} else {
		m.Cluster = types.StringNull()
	}
	if val, ok := apiData["serviceDescriptor"]; ok && val != nil {
		objMap := val.(map[string]interface{})
		var objModel ServiceDescriptorDataSourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(ctx, &objModel, basetypes.ObjectAsOptions{})
		}
		d := objModel.RefreshFromAPI(ctx, objMap)
		diags.Append(d...)
		obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
		diags.Append(d...)
		m.ServiceDescriptor = obj
	} else {
		m.ServiceDescriptor = types.ObjectNull(ServiceDescriptorDataSourceModel{}.AttributeTypes())
	}

	return diags
}

func (m *ServiceRefDataSourceModel) Merge(remote *ServiceRefDataSourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Cluster.IsNull() || m.Cluster.IsUnknown() {
		m.Cluster = remote.Cluster
	}
	if m.ServiceDescriptor.IsNull() || m.ServiceDescriptor.IsUnknown() {
		m.ServiceDescriptor = remote.ServiceDescriptor
	} else {
		var localObj ServiceDescriptorDataSourceModel
		var remoteObj ServiceDescriptorDataSourceModel
		if !m.ServiceDescriptor.IsNull() && !m.ServiceDescriptor.IsUnknown() {
			m.ServiceDescriptor.As(context.Background(), &localObj, basetypes.ObjectAsOptions{})
		}
		if !remote.ServiceDescriptor.IsNull() && !remote.ServiceDescriptor.IsUnknown() {
			remote.ServiceDescriptor.As(context.Background(), &remoteObj, basetypes.ObjectAsOptions{})
		}
		localObj.Merge(&remoteObj)
		obj, diags := types.ObjectValueFrom(context.Background(), localObj.AttributeTypes(), localObj)
		if !diags.HasError() {
			m.ServiceDescriptor = obj
		}
	}
}

type MaintainceWindowDataSourceModel struct {
	StartHour types.Int64  `tfsdk:"start_hour"`
	EndHour   types.Int64  `tfsdk:"end_hour"`
	Weekdays  types.String `tfsdk:"weekdays"`
}

func (v MaintainceWindowDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"start_hour": types.Int64Type,
		"end_hour":   types.Int64Type,
		"weekdays":   types.StringType,
	}
}

func (m *MaintainceWindowDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["startHour"]; ok && val != nil {
		m.StartHour = types.Int64Value(int64(val.(float64)))
	} else {
		m.StartHour = types.Int64Null()
	}
	if val, ok := apiData["endHour"]; ok && val != nil {
		m.EndHour = types.Int64Value(int64(val.(float64)))
	} else {
		m.EndHour = types.Int64Null()
	}
	if val, ok := apiData["weekdays"]; ok && val != nil {
		m.Weekdays = types.StringValue(val.(string))
	} else {
		m.Weekdays = types.StringNull()
	}

	return diags
}

func (m *MaintainceWindowDataSourceModel) Merge(remote *MaintainceWindowDataSourceModel) {
	if m.StartHour.IsNull() || m.StartHour.IsUnknown() {
		m.StartHour = remote.StartHour
	}
	if m.EndHour.IsNull() || m.EndHour.IsUnknown() {
		m.EndHour = remote.EndHour
	}
	if m.Weekdays.IsNull() || m.Weekdays.IsUnknown() {
		m.Weekdays = remote.Weekdays
	}
}
