// Code generated by generator.py. DO NOT EDIT.

package types

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BackupsDataSourceModel struct {
	AutoBackup          types.Bool   `tfsdk:"auto_backup"`
	BackupMethod        types.String `tfsdk:"backup_method"`
	BackupPolicyName    types.String `tfsdk:"backup_policy_name"`
	BackupRepo          types.String `tfsdk:"backup_repo"`
	BackupType          types.String `tfsdk:"backup_type"`
	CompletionTimestamp types.String `tfsdk:"completion_timestamp"`
	CreationTimestamp   types.String `tfsdk:"creation_timestamp"`
	Duration            types.String `tfsdk:"duration"`
	Name                types.String `tfsdk:"name"`
	OrgName             types.String `tfsdk:"org_name"`
	SnapshotVolumes     types.Bool   `tfsdk:"snapshot_volumes"`
	SourceCluster       types.String `tfsdk:"source_cluster"`
	StartTimestamp      types.String `tfsdk:"start_timestamp"`
	Status              types.String `tfsdk:"status"`
	TimeRangeEnd        types.String `tfsdk:"time_range_end"`
	TimeRangeStart      types.String `tfsdk:"time_range_start"`
	TotalSize           types.String `tfsdk:"total_size"`
	FailureReason       types.String `tfsdk:"failure_reason"`
	Extras              types.String `tfsdk:"extras"`
	Path                types.String `tfsdk:"path"`
	RetentionPeriod     types.String `tfsdk:"retention_period"`
	Expiration          types.String `tfsdk:"expiration"`
	Id                  types.String `tfsdk:"id"`
	ClusterId           types.String `tfsdk:"cluster_id"`
	CloudProvider       types.String `tfsdk:"cloud_provider"`
	CloudRegion         types.String `tfsdk:"cloud_region"`
	EnvironmentName     types.String `tfsdk:"environment_name"`
	Engine              types.String `tfsdk:"engine"`
	ParentBackupName    types.String `tfsdk:"parent_backup_name"`
	BaseBackupName      types.String `tfsdk:"base_backup_name"`
	EncryptionKeyName   types.String `tfsdk:"encryption_key_name"`
	TargetPods          types.List   `tfsdk:"target_pods"`
	Parameters          types.List   `tfsdk:"parameters"`
	SelectedObjects     types.List   `tfsdk:"selected_objects"`
}

func (m *BackupsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["autoBackup"]; ok && val != nil {
		m.AutoBackup = types.BoolValue(val.(bool))
	} else {
		m.AutoBackup = types.BoolNull()
	}
	if val, ok := apiData["backupMethod"]; ok && val != nil {
		m.BackupMethod = types.StringValue(val.(string))
	} else {
		m.BackupMethod = types.StringNull()
	}
	if val, ok := apiData["backupPolicyName"]; ok && val != nil {
		m.BackupPolicyName = types.StringValue(val.(string))
	} else {
		m.BackupPolicyName = types.StringNull()
	}
	if val, ok := apiData["backupRepo"]; ok && val != nil {
		m.BackupRepo = types.StringValue(val.(string))
	} else {
		m.BackupRepo = types.StringNull()
	}
	if val, ok := apiData["backupType"]; ok && val != nil {
		m.BackupType = types.StringValue(val.(string))
	} else {
		m.BackupType = types.StringNull()
	}
	if val, ok := apiData["completionTimestamp"]; ok && val != nil {
		m.CompletionTimestamp = types.StringValue(val.(string))
	} else {
		m.CompletionTimestamp = types.StringNull()
	}
	if val, ok := apiData["creationTimestamp"]; ok && val != nil {
		m.CreationTimestamp = types.StringValue(val.(string))
	} else {
		m.CreationTimestamp = types.StringNull()
	}
	if val, ok := apiData["duration"]; ok && val != nil {
		m.Duration = types.StringValue(val.(string))
	} else {
		m.Duration = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["orgName"]; ok && val != nil {
		m.OrgName = types.StringValue(val.(string))
	} else {
		m.OrgName = types.StringNull()
	}
	if val, ok := apiData["snapshotVolumes"]; ok && val != nil {
		m.SnapshotVolumes = types.BoolValue(val.(bool))
	} else {
		m.SnapshotVolumes = types.BoolNull()
	}
	if val, ok := apiData["sourceCluster"]; ok && val != nil {
		m.SourceCluster = types.StringValue(val.(string))
	} else {
		m.SourceCluster = types.StringNull()
	}
	if val, ok := apiData["startTimestamp"]; ok && val != nil {
		m.StartTimestamp = types.StringValue(val.(string))
	} else {
		m.StartTimestamp = types.StringNull()
	}
	if val, ok := apiData["status"]; ok && val != nil {
		m.Status = types.StringValue(val.(string))
	} else {
		m.Status = types.StringNull()
	}
	if val, ok := apiData["timeRangeEnd"]; ok && val != nil {
		m.TimeRangeEnd = types.StringValue(val.(string))
	} else {
		m.TimeRangeEnd = types.StringNull()
	}
	if val, ok := apiData["timeRangeStart"]; ok && val != nil {
		m.TimeRangeStart = types.StringValue(val.(string))
	} else {
		m.TimeRangeStart = types.StringNull()
	}
	if val, ok := apiData["totalSize"]; ok && val != nil {
		m.TotalSize = types.StringValue(val.(string))
	} else {
		m.TotalSize = types.StringNull()
	}
	if val, ok := apiData["failureReason"]; ok && val != nil {
		m.FailureReason = types.StringValue(val.(string))
	} else {
		m.FailureReason = types.StringNull()
	}
	if val, ok := apiData["extras"]; ok && val != nil {
		m.Extras = types.StringValue(val.(string))
	} else {
		m.Extras = types.StringNull()
	}
	if val, ok := apiData["path"]; ok && val != nil {
		m.Path = types.StringValue(val.(string))
	} else {
		m.Path = types.StringNull()
	}
	if val, ok := apiData["retentionPeriod"]; ok && val != nil {
		m.RetentionPeriod = types.StringValue(val.(string))
	} else {
		m.RetentionPeriod = types.StringNull()
	}
	if val, ok := apiData["expiration"]; ok && val != nil {
		m.Expiration = types.StringValue(val.(string))
	} else {
		m.Expiration = types.StringNull()
	}
	if val, ok := apiData["id"]; ok && val != nil {
		m.Id = types.StringValue(val.(string))
	} else {
		m.Id = types.StringNull()
	}
	if val, ok := apiData["clusterId"]; ok && val != nil {
		m.ClusterId = types.StringValue(val.(string))
	} else {
		m.ClusterId = types.StringNull()
	}
	if val, ok := apiData["cloudProvider"]; ok && val != nil {
		m.CloudProvider = types.StringValue(val.(string))
	} else {
		m.CloudProvider = types.StringNull()
	}
	if val, ok := apiData["cloudRegion"]; ok && val != nil {
		m.CloudRegion = types.StringValue(val.(string))
	} else {
		m.CloudRegion = types.StringNull()
	}
	if val, ok := apiData["environmentName"]; ok && val != nil {
		m.EnvironmentName = types.StringValue(val.(string))
	} else {
		m.EnvironmentName = types.StringNull()
	}
	if val, ok := apiData["engine"]; ok && val != nil {
		m.Engine = types.StringValue(val.(string))
	} else {
		m.Engine = types.StringNull()
	}
	if val, ok := apiData["parentBackupName"]; ok && val != nil {
		m.ParentBackupName = types.StringValue(val.(string))
	} else {
		m.ParentBackupName = types.StringNull()
	}
	if val, ok := apiData["baseBackupName"]; ok && val != nil {
		m.BaseBackupName = types.StringValue(val.(string))
	} else {
		m.BaseBackupName = types.StringNull()
	}
	if val, ok := apiData["encryptionKeyName"]; ok && val != nil {
		m.EncryptionKeyName = types.StringValue(val.(string))
	} else {
		m.EncryptionKeyName = types.StringNull()
	}
	if val, ok := apiData["targetPods"]; ok && val != nil {
		var items []attr.Value
		for _, item := range val.([]interface{}) {
			items = append(items, types.StringValue(item.(string)))
		}
		list, d := types.ListValue(types.StringType, items)
		diags.Append(d...)
		m.TargetPods = list
	} else {
		m.TargetPods = types.ListNull(types.StringType)
	}
	if val, ok := apiData["parameters"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ParametersDataSourceModel
		if !m.Parameters.IsNull() && !m.Parameters.IsUnknown() {
			m.Parameters.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ParametersDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ParametersDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Parameters = list
	} else {
		m.Parameters = types.ListNull(types.ObjectType{AttrTypes: ParametersDataSourceModel{}.AttributeTypes()})
	}
	if val, ok := apiData["selectedObjects"]; ok && val != nil {
		var items []attr.Value
		var oldElements []SelectedObjectsDataSourceModel
		if !m.SelectedObjects.IsNull() && !m.SelectedObjects.IsUnknown() {
			m.SelectedObjects.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel SelectedObjectsDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: SelectedObjectsDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.SelectedObjects = list
	} else {
		m.SelectedObjects = types.ListNull(types.ObjectType{AttrTypes: SelectedObjectsDataSourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *BackupsDataSourceModel) Merge(remote *BackupsDataSourceModel) {
	if m.AutoBackup.IsNull() || m.AutoBackup.IsUnknown() {
		m.AutoBackup = remote.AutoBackup
	}
	if m.BackupMethod.IsNull() || m.BackupMethod.IsUnknown() {
		m.BackupMethod = remote.BackupMethod
	}
	if m.BackupPolicyName.IsNull() || m.BackupPolicyName.IsUnknown() {
		m.BackupPolicyName = remote.BackupPolicyName
	}
	if m.BackupRepo.IsNull() || m.BackupRepo.IsUnknown() {
		m.BackupRepo = remote.BackupRepo
	}
	if m.BackupType.IsNull() || m.BackupType.IsUnknown() {
		m.BackupType = remote.BackupType
	}
	if m.CompletionTimestamp.IsNull() || m.CompletionTimestamp.IsUnknown() {
		m.CompletionTimestamp = remote.CompletionTimestamp
	}
	if m.CreationTimestamp.IsNull() || m.CreationTimestamp.IsUnknown() {
		m.CreationTimestamp = remote.CreationTimestamp
	}
	if m.Duration.IsNull() || m.Duration.IsUnknown() {
		m.Duration = remote.Duration
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.OrgName.IsNull() || m.OrgName.IsUnknown() {
		m.OrgName = remote.OrgName
	}
	if m.SnapshotVolumes.IsNull() || m.SnapshotVolumes.IsUnknown() {
		m.SnapshotVolumes = remote.SnapshotVolumes
	}
	if m.SourceCluster.IsNull() || m.SourceCluster.IsUnknown() {
		m.SourceCluster = remote.SourceCluster
	}
	if m.StartTimestamp.IsNull() || m.StartTimestamp.IsUnknown() {
		m.StartTimestamp = remote.StartTimestamp
	}
	if m.Status.IsNull() || m.Status.IsUnknown() {
		m.Status = remote.Status
	}
	if m.TimeRangeEnd.IsNull() || m.TimeRangeEnd.IsUnknown() {
		m.TimeRangeEnd = remote.TimeRangeEnd
	}
	if m.TimeRangeStart.IsNull() || m.TimeRangeStart.IsUnknown() {
		m.TimeRangeStart = remote.TimeRangeStart
	}
	if m.TotalSize.IsNull() || m.TotalSize.IsUnknown() {
		m.TotalSize = remote.TotalSize
	}
	if m.FailureReason.IsNull() || m.FailureReason.IsUnknown() {
		m.FailureReason = remote.FailureReason
	}
	if m.Extras.IsNull() || m.Extras.IsUnknown() {
		m.Extras = remote.Extras
	}
	if m.Path.IsNull() || m.Path.IsUnknown() {
		m.Path = remote.Path
	}
	if m.RetentionPeriod.IsNull() || m.RetentionPeriod.IsUnknown() {
		m.RetentionPeriod = remote.RetentionPeriod
	}
	if m.Expiration.IsNull() || m.Expiration.IsUnknown() {
		m.Expiration = remote.Expiration
	}
	if m.Id.IsNull() || m.Id.IsUnknown() {
		m.Id = remote.Id
	}
	if m.ClusterId.IsNull() || m.ClusterId.IsUnknown() {
		m.ClusterId = remote.ClusterId
	}
	if m.CloudProvider.IsNull() || m.CloudProvider.IsUnknown() {
		m.CloudProvider = remote.CloudProvider
	}
	if m.CloudRegion.IsNull() || m.CloudRegion.IsUnknown() {
		m.CloudRegion = remote.CloudRegion
	}
	if m.EnvironmentName.IsNull() || m.EnvironmentName.IsUnknown() {
		m.EnvironmentName = remote.EnvironmentName
	}
	if m.Engine.IsNull() || m.Engine.IsUnknown() {
		m.Engine = remote.Engine
	}
	if m.ParentBackupName.IsNull() || m.ParentBackupName.IsUnknown() {
		m.ParentBackupName = remote.ParentBackupName
	}
	if m.BaseBackupName.IsNull() || m.BaseBackupName.IsUnknown() {
		m.BaseBackupName = remote.BaseBackupName
	}
	if m.EncryptionKeyName.IsNull() || m.EncryptionKeyName.IsUnknown() {
		m.EncryptionKeyName = remote.EncryptionKeyName
	}
	if m.TargetPods.IsNull() || m.TargetPods.IsUnknown() {
		m.TargetPods = remote.TargetPods
	}
	if m.Parameters.IsNull() || m.Parameters.IsUnknown() {
		m.Parameters = remote.Parameters
	} else {
		var localList []ParametersDataSourceModel
		var remoteList []ParametersDataSourceModel
		if !m.Parameters.IsNull() && !m.Parameters.IsUnknown() {
			m.Parameters.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Parameters.IsNull() && !remote.Parameters.IsUnknown() {
			remote.Parameters.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ParametersDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Parameters = list
		}
	}
	if m.SelectedObjects.IsNull() || m.SelectedObjects.IsUnknown() {
		m.SelectedObjects = remote.SelectedObjects
	} else {
		var localList []SelectedObjectsDataSourceModel
		var remoteList []SelectedObjectsDataSourceModel
		if !m.SelectedObjects.IsNull() && !m.SelectedObjects.IsUnknown() {
			m.SelectedObjects.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.SelectedObjects.IsNull() && !remote.SelectedObjects.IsUnknown() {
			remote.SelectedObjects.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: SelectedObjectsDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.SelectedObjects = list
		}
	}
}

type ParametersDataSourceModel struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}

func (v ParametersDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":  types.StringType,
		"value": types.StringType,
	}
}

func (m *ParametersDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["value"]; ok && val != nil {
		m.Value = types.StringValue(val.(string))
	} else {
		m.Value = types.StringNull()
	}

	return diags
}

func (m *ParametersDataSourceModel) Merge(remote *ParametersDataSourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.Value.IsNull() || m.Value.IsUnknown() {
		m.Value = remote.Value
	}
}

type SelectedObjectsDataSourceModel struct {
	Type        types.String `tfsdk:"type"`
	Name        types.String `tfsdk:"name"`
	SelectedAll types.Bool   `tfsdk:"selected_all"`
	Children    types.List   `tfsdk:"children"`
}

func (v SelectedObjectsDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"type":         types.StringType,
		"name":         types.StringType,
		"selected_all": types.BoolType,
		"children":     types.ListType{ElemType: types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()}},
	}
}

func (m *SelectedObjectsDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["type"]; ok && val != nil {
		m.Type = types.StringValue(val.(string))
	} else {
		m.Type = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["selectedAll"]; ok && val != nil {
		m.SelectedAll = types.BoolValue(val.(bool))
	} else {
		m.SelectedAll = types.BoolNull()
	}
	if val, ok := apiData["children"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ChildrenDataSourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ChildrenDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Children = list
	} else {
		m.Children = types.ListNull(types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *SelectedObjectsDataSourceModel) Merge(remote *SelectedObjectsDataSourceModel) {
	if m.Type.IsNull() || m.Type.IsUnknown() {
		m.Type = remote.Type
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.SelectedAll.IsNull() || m.SelectedAll.IsUnknown() {
		m.SelectedAll = remote.SelectedAll
	}
	if m.Children.IsNull() || m.Children.IsUnknown() {
		m.Children = remote.Children
	} else {
		var localList []ChildrenDataSourceModel
		var remoteList []ChildrenDataSourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Children.IsNull() && !remote.Children.IsUnknown() {
			remote.Children.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Children = list
		}
	}
}

type ChildrenDataSourceModel struct {
	Type        types.String `tfsdk:"type"`
	Name        types.String `tfsdk:"name"`
	SelectedAll types.Bool   `tfsdk:"selected_all"`
	Children    types.List   `tfsdk:"children"`
}

func (v ChildrenDataSourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"type":         types.StringType,
		"name":         types.StringType,
		"selected_all": types.BoolType,
		"children":     types.ListType{ElemType: types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()}},
	}
}

func (m *ChildrenDataSourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["type"]; ok && val != nil {
		m.Type = types.StringValue(val.(string))
	} else {
		m.Type = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["selectedAll"]; ok && val != nil {
		m.SelectedAll = types.BoolValue(val.(bool))
	} else {
		m.SelectedAll = types.BoolNull()
	}
	if val, ok := apiData["children"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ChildrenDataSourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ChildrenDataSourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Children = list
	} else {
		m.Children = types.ListNull(types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *ChildrenDataSourceModel) Merge(remote *ChildrenDataSourceModel) {
	if m.Type.IsNull() || m.Type.IsUnknown() {
		m.Type = remote.Type
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.SelectedAll.IsNull() || m.SelectedAll.IsUnknown() {
		m.SelectedAll = remote.SelectedAll
	}
	if m.Children.IsNull() || m.Children.IsUnknown() {
		m.Children = remote.Children
	} else {
		var localList []ChildrenDataSourceModel
		var remoteList []ChildrenDataSourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Children.IsNull() && !remote.Children.IsUnknown() {
			remote.Children.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ChildrenDataSourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Children = list
		}
	}
}
