// Code generated by generator.py. DO NOT EDIT.

package types

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type BackupsResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	BackupType      types.String `tfsdk:"backup_type"`
	BackupMethod    types.String `tfsdk:"backup_method"`
	Component       types.String `tfsdk:"component"`
	RetentionPeriod types.String `tfsdk:"retention_period"`
	Parameters      types.Map    `tfsdk:"parameters"`
	SelectedObjects types.List   `tfsdk:"selected_objects"`
}

func (m *BackupsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["backupType"]; ok && val != nil {
		m.BackupType = types.StringValue(val.(string))
	} else {
		m.BackupType = types.StringNull()
	}
	if val, ok := apiData["backupMethod"]; ok && val != nil {
		m.BackupMethod = types.StringValue(val.(string))
	} else {
		m.BackupMethod = types.StringNull()
	}
	if val, ok := apiData["component"]; ok && val != nil {
		m.Component = types.StringValue(val.(string))
	} else {
		m.Component = types.StringNull()
	}
	if val, ok := apiData["retentionPeriod"]; ok && val != nil {
		m.RetentionPeriod = types.StringValue(val.(string))
	} else {
		m.RetentionPeriod = types.StringNull()
	}
	if val, ok := apiData["parameters"]; ok && val != nil {
		mapValues := make(map[string]attr.Value)
		for k, v := range val.(map[string]interface{}) {
			mapValues[k] = types.StringValue(v.(string))
		}
		m.Parameters, _ = types.MapValue(types.StringType, mapValues)
	} else {
		m.Parameters = types.MapNull(types.StringType)
	}
	if val, ok := apiData["selectedObjects"]; ok && val != nil {
		var items []attr.Value
		var oldElements []SelectedObjectsResourceModel
		if !m.SelectedObjects.IsNull() && !m.SelectedObjects.IsUnknown() {
			m.SelectedObjects.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel SelectedObjectsResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: SelectedObjectsResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.SelectedObjects = list
	} else {
		m.SelectedObjects = types.ListNull(types.ObjectType{AttrTypes: SelectedObjectsResourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *BackupsResourceModel) Merge(remote *BackupsResourceModel) {
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.BackupType.IsNull() || m.BackupType.IsUnknown() {
		m.BackupType = remote.BackupType
	}
	if m.BackupMethod.IsNull() || m.BackupMethod.IsUnknown() {
		m.BackupMethod = remote.BackupMethod
	}
	if m.Component.IsNull() || m.Component.IsUnknown() {
		m.Component = remote.Component
	}
	if m.RetentionPeriod.IsNull() || m.RetentionPeriod.IsUnknown() {
		m.RetentionPeriod = remote.RetentionPeriod
	}
	if m.Parameters.IsNull() || m.Parameters.IsUnknown() {
		m.Parameters = remote.Parameters
	}
	if m.SelectedObjects.IsNull() || m.SelectedObjects.IsUnknown() {
		m.SelectedObjects = remote.SelectedObjects
	} else {
		var localList []SelectedObjectsResourceModel
		var remoteList []SelectedObjectsResourceModel
		if !m.SelectedObjects.IsNull() && !m.SelectedObjects.IsUnknown() {
			m.SelectedObjects.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.SelectedObjects.IsNull() && !remote.SelectedObjects.IsUnknown() {
			remote.SelectedObjects.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: SelectedObjectsResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.SelectedObjects = list
		}
	}
}

type SelectedObjectsResourceModel struct {
	Type        types.String `tfsdk:"type"`
	Name        types.String `tfsdk:"name"`
	SelectedAll types.Bool   `tfsdk:"selected_all"`
	Children    types.List   `tfsdk:"children"`
}

func (v SelectedObjectsResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"type":         types.StringType,
		"name":         types.StringType,
		"selected_all": types.BoolType,
		"children":     types.ListType{ElemType: types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()}},
	}
}

func (m *SelectedObjectsResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["type"]; ok && val != nil {
		m.Type = types.StringValue(val.(string))
	} else {
		m.Type = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["selectedAll"]; ok && val != nil {
		m.SelectedAll = types.BoolValue(val.(bool))
	} else {
		m.SelectedAll = types.BoolNull()
	}
	if val, ok := apiData["children"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ChildrenResourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ChildrenResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Children = list
	} else {
		m.Children = types.ListNull(types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *SelectedObjectsResourceModel) Merge(remote *SelectedObjectsResourceModel) {
	if m.Type.IsNull() || m.Type.IsUnknown() {
		m.Type = remote.Type
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.SelectedAll.IsNull() || m.SelectedAll.IsUnknown() {
		m.SelectedAll = remote.SelectedAll
	}
	if m.Children.IsNull() || m.Children.IsUnknown() {
		m.Children = remote.Children
	} else {
		var localList []ChildrenResourceModel
		var remoteList []ChildrenResourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Children.IsNull() && !remote.Children.IsUnknown() {
			remote.Children.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Children = list
		}
	}
}

type ChildrenResourceModel struct {
	Type        types.String `tfsdk:"type"`
	Name        types.String `tfsdk:"name"`
	SelectedAll types.Bool   `tfsdk:"selected_all"`
	Children    types.List   `tfsdk:"children"`
}

func (v ChildrenResourceModel) AttributeTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"type":         types.StringType,
		"name":         types.StringType,
		"selected_all": types.BoolType,
		"children":     types.ListType{ElemType: types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()}},
	}
}

func (m *ChildrenResourceModel) RefreshFromAPI(ctx context.Context, apiData map[string]interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	if val, ok := apiData["type"]; ok && val != nil {
		m.Type = types.StringValue(val.(string))
	} else {
		m.Type = types.StringNull()
	}
	if val, ok := apiData["name"]; ok && val != nil {
		m.Name = types.StringValue(val.(string))
	} else {
		m.Name = types.StringNull()
	}
	if val, ok := apiData["selectedAll"]; ok && val != nil {
		m.SelectedAll = types.BoolValue(val.(bool))
	} else {
		m.SelectedAll = types.BoolNull()
	}
	if val, ok := apiData["children"]; ok && val != nil {
		var items []attr.Value
		var oldElements []ChildrenResourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(ctx, &oldElements, false)
		}
		for i, item := range val.([]interface{}) {
			objMap := item.(map[string]interface{})
			var objModel ChildrenResourceModel
			if i < len(oldElements) {
				objModel = oldElements[i]
			}
			d := objModel.RefreshFromAPI(ctx, objMap)
			diags.Append(d...)
			obj, d := types.ObjectValueFrom(ctx, objModel.AttributeTypes(), objModel)
			diags.Append(d...)
			items = append(items, obj)
		}
		list, d := types.ListValue(types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()}, items)
		diags.Append(d...)
		m.Children = list
	} else {
		m.Children = types.ListNull(types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()})
	}

	return diags
}

func (m *ChildrenResourceModel) Merge(remote *ChildrenResourceModel) {
	if m.Type.IsNull() || m.Type.IsUnknown() {
		m.Type = remote.Type
	}
	if m.Name.IsNull() || m.Name.IsUnknown() {
		m.Name = remote.Name
	}
	if m.SelectedAll.IsNull() || m.SelectedAll.IsUnknown() {
		m.SelectedAll = remote.SelectedAll
	}
	if m.Children.IsNull() || m.Children.IsUnknown() {
		m.Children = remote.Children
	} else {
		var localList []ChildrenResourceModel
		var remoteList []ChildrenResourceModel
		if !m.Children.IsNull() && !m.Children.IsUnknown() {
			m.Children.ElementsAs(context.Background(), &localList, false)
		}
		if !remote.Children.IsNull() && !remote.Children.IsUnknown() {
			remote.Children.ElementsAs(context.Background(), &remoteList, false)
		}

		var mergedList []attr.Value
		// Iterate through remote items to preserve server-generated items
		for i, remoteItem := range remoteList {
			if i < len(localList) {
				// If local has this item, merge remote into local
				localList[i].Merge(&remoteItem)
				obj, diags := types.ObjectValueFrom(context.Background(), localList[i].AttributeTypes(), localList[i])
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			} else {
				// If local doesn't have it (e.g. server added it), append remote item
				obj, diags := types.ObjectValueFrom(context.Background(), remoteItem.AttributeTypes(), remoteItem)
				if !diags.HasError() {
					mergedList = append(mergedList, obj)
				}
			}
		}

		list, diags := types.ListValue(types.ObjectType{AttrTypes: ChildrenResourceModel{}.AttributeTypes()}, mergedList)
		if !diags.HasError() {
			m.Children = list
		}
	}
}
