// Code generated by generator.py. DO NOT EDIT.

package datasource

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func BackupsDataSourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{

			"auto_backup": schema.BoolAttribute{
				Computed:    true,
				Description: "autoBackup or not",
			},

			"backup_method": schema.StringAttribute{
				Computed:    true,
				Description: "Backup Method.",
			},

			"backup_policy_name": schema.StringAttribute{
				Computed:    true,
				Description: "Which backupPolicy is applied to perform this backup",
			},

			"backup_repo": schema.StringAttribute{
				Computed:    true,
				Description: "backupRepo is the name of backupRepo and it is used to store the backup data",
			},

			"backup_type": schema.StringAttribute{
				Computed:    true,
				Description: "the type of backup",
			},

			"completion_timestamp": schema.StringAttribute{
				Computed:    true,
				Description: "Date/time when the backup finished being processed.",
			},

			"creation_timestamp": schema.StringAttribute{
				Computed:    true,
				Description: "Date/time when the backup was created.",
			},

			"duration": schema.StringAttribute{
				Computed:    true,
				Description: "The duration time of backup execution. When converted to a string, the form is \"1h2m0.5s\".",
			},

			"name": schema.StringAttribute{
				Computed:    true,
				Description: "name of the backup",
			},

			"org_name": schema.StringAttribute{
				Computed:    true,
				Description: "orgName records the organization name for this backup.",
			},

			"snapshot_volumes": schema.BoolAttribute{
				Computed:    true,
				Description: "snapshotVolumes specifies whether to take snapshots of persistent volumes to back up",
			},

			"source_cluster": schema.StringAttribute{
				Computed:    true,
				Description: "sourceCluster records the source cluster information for this backup.",
			},

			"start_timestamp": schema.StringAttribute{
				Computed:    true,
				Description: "Date/time when the backup started being processed.",
			},

			"status": schema.StringAttribute{
				Computed:    true,
				Description: "The current status. Valid values are New, InProgress, Completed, Failed.",
			},

			"time_range_end": schema.StringAttribute{
				Computed:    true,
				Description: "timeRangeEnd records the end time of the backup.",
			},

			"time_range_start": schema.StringAttribute{
				Computed:    true,
				Description: "timeRangeStart records the start time of the backup.",
			},

			"total_size": schema.StringAttribute{
				Computed:    true,
				Description: "Backup total size. A string with capacity units in the form of \"1Gi\", \"1Mi\", \"1Ki\".",
			},

			"failure_reason": schema.StringAttribute{
				Computed: true,
			},

			"extras": schema.StringAttribute{
				Computed: true,
			},

			"path": schema.StringAttribute{
				Computed:    true,
				Description: "the path of backup files",
			},

			"retention_period": schema.StringAttribute{
				Computed:    true,
				Description: "determines a duration up to which the backup should be kept",
			},

			"expiration": schema.StringAttribute{
				Computed:    true,
				Description: "indicates when this backup becomes eligible for garbage collection",
			},

			"id": schema.StringAttribute{
				Computed:    true,
				Description: "the backup id",
			},

			"cluster_id": schema.StringAttribute{
				Computed:    true,
				Description: "the id of cluster that backup belong to",
			},

			"cloud_provider": schema.StringAttribute{
				Computed:    true,
				Description: "the cloud provider",
			},

			"cloud_region": schema.StringAttribute{
				Computed:    true,
				Description: "the cloud region",
			},

			"environment_name": schema.StringAttribute{
				Computed:    true,
				Description: "the environment name",
			},

			"engine": schema.StringAttribute{
				Computed:    true,
				Description: "the cluster engine",
			},

			"parent_backup_name": schema.StringAttribute{
				Computed:    true,
				Description: "the parent backup name",
			},

			"base_backup_name": schema.StringAttribute{
				Computed:    true,
				Description: "the base backup name",
			},

			"encryption_key_name": schema.StringAttribute{
				Computed:    true,
				Description: "the key name used for encryption",
			},

			"target_pods": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
				Description: "backup target pods",
			},

			"parameters": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"name": schema.StringAttribute{
							Computed:    true,
							Description: "the name of parameter",
						},

						"value": schema.StringAttribute{
							Computed:    true,
							Description: "the value of parameter",
						},
					},
				},
				Computed:    true,
				Description: "backup parameters",
			},

			"selected_objects": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"type": schema.StringAttribute{
							Computed:    true,
							Description: "the type of the node",
						},

						"name": schema.StringAttribute{
							Computed:    true,
							Description: "the name of the node",
						},

						"selected_all": schema.BoolAttribute{
							Computed:    true,
							Description: "whether all children nodes are selected",
						},

						"children": schema.DynamicAttribute{
							Computed:    true,
							Description: "children nodes",
						},
					},
				},
				Computed:    true,
				Description: "backup selected objects",
			},
		},
	}
}
