// Code generated by generator.py. DO NOT EDIT.

package datasource

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func ClustersDataSourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{

			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Cluster ID",
			},

			"parent_id": schema.StringAttribute{
				Computed:    true,
				Description: "When two clusters have a relationship, parentId records the parent cluster id.Can be empty when there is no relationship",
			},

			"parent_name": schema.StringAttribute{
				Computed:    true,
				Description: "the name of parent cluster",
			},

			"parent_display_name": schema.StringAttribute{
				Computed:    true,
				Description: "the display name of parent cluster",
			},

			"cluster_type": schema.StringAttribute{
				Computed:    true,
				Description: "Describes the type of cluster",
			},

			"delay": schema.Float64Attribute{
				Computed: true,
			},

			"org_name": schema.StringAttribute{
				Computed:    true,
				Description: "Org Name",
			},

			"cloud_provider": schema.StringAttribute{
				Computed:    true,
				Description: "Cloud Provider",
			},

			"environment_id": schema.StringAttribute{
				Computed:    true,
				Description: "ID of the environment",
			},

			"environment_name": schema.StringAttribute{
				Computed:    true,
				Description: "Environment Name",
			},

			"cloud_region": schema.StringAttribute{
				Computed:    true,
				Description: "Cloud Region",
			},

			"project": schema.StringAttribute{
				Computed:    true,
				Description: "Name of project, it is the alias of environment namespace",
			},

			"name": schema.StringAttribute{
				Computed:    true,
				Description: "Name of cluster. Name must be unique within an Org",
			},

			"hash": schema.StringAttribute{
				Computed:    true,
				Description: "Hash of cluster. Name must be unique within an Org",
			},

			"engine": schema.StringAttribute{
				Computed:    true,
				Description: "Cluster Application Engine",
			},

			"version": schema.StringAttribute{
				Computed:    true,
				Description: "Cluster Application Version",
			},

			"termination_policy": schema.StringAttribute{
				Computed:    true,
				Description: "The termination policy of cluster.",
			},

			"tls_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "Enable the cluster to provide TLS connection or not.",
			},

			"node_port_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "Enable the cluster to provide NodePort service or not.",
			},

			"status": schema.StringAttribute{
				Computed:    true,
				Description: "Cluster Status",
			},

			"created_at": schema.StringAttribute{
				Computed:    true,
				Description: "CreatedAt is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists",
			},

			"updated_at": schema.StringAttribute{
				Computed:    true,
				Description: "UpdatedAt is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists",
			},

			"mode": schema.StringAttribute{
				Computed:    true,
				Description: "Cluster topology mode",
			},

			"proxy_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "Proxy Enabled",
			},

			"extra": schema.
				DynamicAttribute{
				Computed:    true,
				Description: "Extra configuration for cluster",
			},

			"single_zone": schema.BoolAttribute{
				Computed:    true,
				Description: "Use single availability zones",
			},

			"pod_anti_affinity_enabled": schema.BoolAttribute{
				Computed:    true,
				Description: "Enable pod antiaffinity for cluster",
			},

			"node_group": schema.StringAttribute{
				Computed:    true,
				Description: "Specify a NodeGroup for the cluster",
			},

			"code_short": schema.StringAttribute{
				Computed:    true,
				Description: "Cluster main component codeShort",
			},

			"display_name": schema.StringAttribute{
				Computed:    true,
				Description: "Display name of cluster.",
			},

			"static": schema.BoolAttribute{
				Computed:    true,
				Description: "if cluster is static cluster",
			},

			"network_mode": schema.StringAttribute{
				Computed: true,
			},

			"availability_zones": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
				Description: "Availability Zones",
			},

			"param_tpls": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"component": schema.StringAttribute{
							Computed:    true,
							Description: "component type, refer to componentDef and support NamePrefix",
						},

						"param_tpl_name": schema.StringAttribute{
							Computed:    true,
							Description: "name of assigned parameter template",
						},

						"param_tpl_id": schema.StringAttribute{
							Computed:    true,
							Description: "id of parameter template",
						},

						"org_name": schema.StringAttribute{
							Computed:    true,
							Description: "org name of the parameter template",
						},

						"param_tpl_partition": schema.StringAttribute{
							Computed: true,
						},
					},
				},
				Computed:    true,
				Description: "Items is the list of parameter template in the list",
			},

			"components": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"name": schema.StringAttribute{
							Computed:    true,
							Description: "component name",
						},

						"component": schema.StringAttribute{
							Computed:    true,
							Description: "component type, refer to componentDef and support NamePrefix",
						},

						"comp_num": schema.Int64Attribute{
							Computed:    true,
							Description: "number of components",
						},

						"replicas": schema.Int64Attribute{
							Computed:    true,
							Description: "The number of replicas, for standalone mode, the replicas is 1, for raftGroup mode, the default replicas is 3.",
						},

						"class_code": schema.StringAttribute{
							Computed: true,
						},

						"cpu": schema.Float64Attribute{
							Computed:    true,
							Description: "CPU cores.",
						},

						"memory": schema.Float64Attribute{
							Computed:    true,
							Description: "Memory, the unit is Gi.",
						},

						"storage_class": schema.StringAttribute{
							Computed:    true,
							Description: "StorageClass name",
						},

						"volumes": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{

									"name": schema.StringAttribute{
										Computed:    true,
										Description: "volume name",
									},

									"storage": schema.Float64Attribute{
										Computed:    true,
										Description: "Storage size, the unit is Gi.",
									},

									"io_limits": schema.SingleNestedAttribute{
										Attributes: map[string]schema.Attribute{

											"read_iops": schema.Int64Attribute{
												Computed: true,
											},

											"write_iops": schema.Int64Attribute{
												Computed: true,
											},

											"read_bps": schema.Int64Attribute{
												Computed: true,
											},

											"write_bps": schema.Int64Attribute{
												Computed: true,
											},
										},
										Computed:    true,
										Description: "IO Quantity describes IOPS and BPS of a volume",
									},

									"io_reserves": schema.SingleNestedAttribute{
										Attributes: map[string]schema.Attribute{

											"read_iops": schema.Int64Attribute{
												Computed: true,
											},

											"write_iops": schema.Int64Attribute{
												Computed: true,
											},

											"read_bps": schema.Int64Attribute{
												Computed: true,
											},

											"write_bps": schema.Int64Attribute{
												Computed: true,
											},
										},
										Computed:    true,
										Description: "IO Quantity describes IOPS and BPS of a volume",
									},
								},
							},
							Computed: true,
						},

						"code_short": schema.StringAttribute{
							Computed:    true,
							Description: "Cluster main component codeShort",
						},

						"system_account_secret_name": schema.StringAttribute{
							Computed:    true,
							Description: "The name of the secret that contains the system account credentials",
						},
					},
				},
				Computed:    true,
				Description: "Components is the list of components",
			},

			"init_options": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"component": schema.StringAttribute{
							Computed:    true,
							Description: "component type, refer to componentDef and support NamePrefix'",
						},

						"init_params": schema.
							MapAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},

						"spec_name": schema.StringAttribute{
							Computed:    true,
							Description: "config spec name",
						},
					},
				},
				Computed:    true,
				Description: "InitOptions is the list of init option",
			},

			"service_refs": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"name": schema.StringAttribute{
							Computed:    true,
							Description: "refers to the serviceRef name defined in engineoption",
						},

						"cluster": schema.StringAttribute{
							Computed:    true,
							Description: "the cluster name that will be used in serviceRef. The referenced cluster should  be at the same organization as the current cluster. ",
						},

						"service_descriptor": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{

								"host": schema.StringAttribute{
									Computed: true,
								},

								"port": schema.StringAttribute{
									Computed: true,
								},

								"endpoint": schema.StringAttribute{
									Computed: true,
								},

								"username": schema.StringAttribute{
									Computed: true,
								},

								"password": schema.StringAttribute{
									Computed: true,
								},
							},
							Computed:    true,
							Description: "serviceDescriptor that will be used in serviceRef. The field definition is in line with kubeblocks.",
						},
					},
				},
				Computed:    true,
				Description: "serviceRefs used by this cluster",
			},

			"referenced_by": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"name": schema.StringAttribute{
							Computed:    true,
							Description: "refers to the serviceRef name defined in engineoption",
						},

						"cluster": schema.StringAttribute{
							Computed:    true,
							Description: "the cluster name that will be used in serviceRef. The referenced cluster should  be at the same organization as the current cluster. ",
						},

						"service_descriptor": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{

								"host": schema.StringAttribute{
									Computed: true,
								},

								"port": schema.StringAttribute{
									Computed: true,
								},

								"endpoint": schema.StringAttribute{
									Computed: true,
								},

								"username": schema.StringAttribute{
									Computed: true,
								},

								"password": schema.StringAttribute{
									Computed: true,
								},
							},
							Computed:    true,
							Description: "serviceDescriptor that will be used in serviceRef. The field definition is in line with kubeblocks.",
						},
					},
				},
				Computed:    true,
				Description: "this list of objects (currently, object is a cluster) that uses this cluster as a serviceRef",
			},

			"license": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{

					"id": schema.StringAttribute{
						Computed: true,
					},

					"name": schema.StringAttribute{
						Computed: true,
					},

					"expired_at": schema.StringAttribute{
						Computed: true,
					},

					"key": schema.StringAttribute{
						Computed: true,
					},

					"keys": schema.
						MapAttribute{
						ElementType: types.StringType,
						Computed:    true,
					},
				},
				Computed: true,
			},

			"backup": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{

					"pitr_enabled": schema.BoolAttribute{
						Computed:    true,
						Description: "PITREnabled or not",
					},

					"continuous_backup_method": schema.StringAttribute{
						Computed:    true,
						Description: "continuous backup method for pitr",
					},

					"auto_backup": schema.BoolAttribute{
						Computed:    true,
						Description: "autoBackup or not",
					},

					"auto_backup_method": schema.StringAttribute{
						Computed:    true,
						Description: "name of the backup method",
					},

					"backup_repo": schema.StringAttribute{
						Computed:    true,
						Description: "backupRepoName is the name of backupRepo and it is used to store the backup data",
					},

					"cron_expression": schema.StringAttribute{
						Computed:    true,
						Description: "cronExpression specifies the cron expression",
					},

					"retention_period": schema.StringAttribute{
						Computed:    true,
						Description: "retentionPeriod specifies the retention period",
					},

					"retention_policy": schema.StringAttribute{
						Computed:    true,
						Description: "backup retention policy when cluster is deleted",
					},

					"snapshot_volumes": schema.BoolAttribute{
						Computed:    true,
						Description: "snapshotVolumes specifies whether to take snapshots of persistent volumes to back up",
					},

					"incremental_backup_enabled": schema.BoolAttribute{
						Computed:    true,
						Description: "specify whether to enable incremental backup",
					},

					"incremental_cron_expression": schema.StringAttribute{
						Computed:    true,
						Description: "the crop expression for incremental backup schedule",
					},
				},
				Computed:    true,
				Description: "clusterBackup is the payload for cluster backup",
			},

			"object_storage_config": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{

					"service_ref": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{

							"name": schema.StringAttribute{
								Computed:    true,
								Description: "refers to the serviceRef name defined in engineoption",
							},

							"cluster": schema.StringAttribute{
								Computed:    true,
								Description: "the cluster name that will be used in serviceRef. The referenced cluster should  be at the same organization as the current cluster. ",
							},

							"service_descriptor": schema.SingleNestedAttribute{
								Attributes: map[string]schema.Attribute{

									"host": schema.StringAttribute{
										Computed: true,
									},

									"port": schema.StringAttribute{
										Computed: true,
									},

									"endpoint": schema.StringAttribute{
										Computed: true,
									},

									"username": schema.StringAttribute{
										Computed: true,
									},

									"password": schema.StringAttribute{
										Computed: true,
									},
								},
								Computed:    true,
								Description: "serviceDescriptor that will be used in serviceRef. The field definition is in line with kubeblocks.",
							},
						},
						Computed:    true,
						Description: "defines a serviceRef that references service provided by other cluster or external service. Only one of cluster or serviceDescriptor field should be set. ",
					},

					"bucket": schema.StringAttribute{
						Computed:    true,
						Description: "the bucket name for the object storage",
					},

					"use_path_style": schema.BoolAttribute{
						Computed:    true,
						Description: "whether the object storage is using path-style. If false, virtual host style will be used.",
					},

					"region": schema.StringAttribute{
						Computed:    true,
						Description: "region to use. If using a s3-compatible service that does not require a region (like minio), leave it blank.",
					},
				},
				Computed:    true,
				Description: "Specify the object storage config for cluster like starrocks",
			},

			"maintaince_window": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{

					"start_hour": schema.Int64Attribute{
						Computed:    true,
						Description: "start hour, must be 0-23, use UTC timezone",
					},

					"end_hour": schema.Int64Attribute{
						Computed:    true,
						Description: "end hour, must be 0-23 and greater than start hour, use UTC timezone",
					},

					"weekdays": schema.StringAttribute{
						Computed:    true,
						Description: "weekdays, comma separated values of 1-7",
					},
				},
				Computed:    true,
				Description: "the maintenance window for a cluster",
			},
		},
	}
}
