// Code generated by generator.py. DO NOT EDIT.

package resource

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func BackupsResourceSchema() schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
			},

			"name": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "name of the backup, if not specified, a name will be generated automatically",
			},

			"backup_type": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "the type of backup",
			},

			"backup_method": schema.StringAttribute{
				Required:    true,
				Description: "specified the backup method",
			},

			"component": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "component of the cluster to back up",
			},

			"retention_period": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "specify the retention period",
			},

			"parameters": schema.
				MapAttribute{
				ElementType: types.StringType,
				Computed:    true,
				Optional:    true,
				Description: "parameters for the backup",
			},

			"selected_objects": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{

						"type": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: "the type of the node",
						},

						"name": schema.StringAttribute{
							Computed:    true,
							Optional:    true,
							Description: "the name of the node",
						},

						"selected_all": schema.BoolAttribute{
							Computed:    true,
							Optional:    true,
							Description: "whether all children nodes are selected",
						},

						"children": schema.DynamicAttribute{
							Computed:    true,
							Optional:    true,
							Description: "children nodes",
						},
					},
				},
				Computed:    true,
				Optional:    true,
				Description: "selected objects for the backup",
			},
		},
	}
}
